language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
os:
  - linux
  - osx
sudo: false

cache:
  - cargo

script:
  - cargo test --no-default-features --features rustc-serialization
  - cargo test --no-default-features --features serde-serialization

env:
  global:
    - RUST_BACKTRACE=1