language: rust
rust: nightly
sudo: false

cache:
  - cargo

script:
  - cargo test --no-default-features --features rustc-serialization
  - cargo test --no-default-features --features serde-serialization
  - cargo test --no-default-features --features response-to-string

env:
  global:
    - RUST_BACKTRACE=1